### PR TITLE
Fix for Android Audio Notifications in Android Marshmallow

### PR DESCRIPTION
**Pull request by pslgoh**
Our RhoMobile app would not be able to play audio notifications in Android 6.0, but would work for older OS versions (Android 5.x or older). 

Our app made use of the Javascript API Rho.Notification.playFile method. Debugging in ADB traced issue back to the NotificationSingleton.java class. 

This update to NotificationSingleton.java class fixed the playfile problem we were experiencing with Android 6.0, and maintained compatibility with older Android OS (API Lvl < 23)

Please consider this pull request to be merged back into origin..

### CODE REVIEW

**Comment by rognar** [comment]
Thanks.
We will merge your changes on next week.

Regards,
Konstantin

**Comment by alex-epifanoff** [comment]
Hello, we've tested notification API on Android 6 and it seems to work OK.
Can you please submit a support ticket on tautechnologies.zendesk.com and provide more details on the specific case you have issues with.

1) Path to the file you play.
2) Provide build.yml of your app
3) Provide rhoconfig.txt of your app
4) Provide sample code.

**Comment by rognar** [comment]
Alex mean that we've tested Rho 5.5.0.4 and it works fine.

**Comment by pslgoh** [comment]
We were having this issue with rhodes 5.4.0, I have retested our application with v5.5.0.4, and can confirm the issue we were having with audio notifications is fixed. 

I will cancel this pull request. Sorry for the trouble, and thank you both for your time. 

Regards, 
Paul

**Pull request closed without merging**
