### PR TITLE
SR EMBPD00164754

### PR DESCRIPTION
**Pull request by fgqw68**
[Camera][WM/CE/Android/ios] - Message field value returned for cancel status is not uniform

### CODE REVIEW

**Comment by fgqw68** [comment]
@NPJ473. please review

**Comment by fgqw68** [comment]
@rhtv43  Please ensure corresponding changes gone to android java files as well

**Comment by ashikd** [comment]
@fgqw68 add CE platform as well in supported platform list

**Comment by fgqw68** [comment]
@ashikd  Thanks. I have updated

**Comment by ashikd** [comment]
Accept with revision

**Comment by fgqw68** [comment]
Thanks

**Pull request merged**
