### PR TITLE
New exitpassword android

### PR DESCRIPTION
**Pull request by qwjn67**
@malayap47 

Please Review the code for ExitPasswordAndroid.

### CODE REVIEW

**Comment by qwjn67** [comment]
@rajak1

Please Review the code for Password on Exit feature for android

**Comment by rajak1** [comment]
I'm guessing setting the password etc will be done based on the setting used in the config.xml (for Enterprise Browser specific). 

Do not expose PerformRealExit to outside (make it private). Use the standard Java convention for method names

**Comment by qwjn67** [comment]
@rajak1 
Yes setting the password will be done based on the settings used in config.xml.
I have changed the  PerformRealExit method to private. can you suggest some good names for this method.

**Comment by qwjn67** [comment]
@rajak1 
If the method is made private it cannot be accessed from PasswordDialog.java file, there is a method  called callExitNow() in passworddialogue.java file which access PerformRealExit method

**Pull request merged**
