### PR TITLE
project files uploaded 

### PR DESCRIPTION
**Pull request by fgqw68**
1) adding csproject and c++/cli project to repository
2) camerabase.cs never getting generated during rake
3) need to delete mediacapture.vcxproj and to retain only MediacaptureLib.vcxproj and MediacaptureImpl.csproj only. we will include MediacaptureLib.vcxproj  in rhodes.sln for debugging purpose
4) when i included mediacapture as an extension in build.yml, csharpextensions.cs file in rhodes.dll looks for amethod MediacaptureFactorycomponent. but cameraruntime.cpp doesn't have this implementation.
5)camera construction in C# project doesn't get strID as argument. this is very much needed to identify whether camera is front or back when a method is invoked.

### CODE REVIEW

**Comment by fgqw68** [comment]
@timashev

**Comment by fgqw68** [comment]
@timashev  as suggested i have uploaded the project files

**Comment by timashev** [comment]
I have fixed everything and committed the changes to the branch, so the Mediacapture extension is built successfully in both my development and production environment (application .XAP file is created as a result).
But I didn't test it on the devices though, just made sure everything is compiled and bundled successfully.

**Comment by fgqw68** [comment]
@timashev  first of all thanks for your great support... I have few queries on the fix
1) is the files CameraImpl.csproj and CameraLib.vcxproj auto generated ones. Or did you rename the existing MediacaptureLib.vcxproj and MediacaptureImpl.csproj to CameraImpl and edited file inclusion manually?
2) Camera constructor still doesn't get the strID to identify the camera instance type. Whenever user makes a call on instance method, I must know whether he invoked call on front or back instance.

3) I had sent a mail to you regarding wp8 javascript bridge interface issue. We are able to make static method invocation. Where as when we try to invoke a instance method after the enumeration. It never invokes the js_notify. Call from javascript never invokes the js_notify event in rhodes.dll. This bridge issue needs to be resolved.

**Comment by timashev** [comment]
@fgqw68
1) I have renamed and edited them manually.
2) I have fixed that. Now auto-generated CameraBase class has 'protected string _strID' member with initial default value of "1". The real value of strID is set in setNativeImpl call, so if you want to catch it, override this method in Camera class (and don't forget to call the parent setNativeImpl first of all). IMPORTANT: you have to re-generate the API files by running either 'rake device:wp8:production' or 'rhogen api <full-path>.xml'

**Comment by fgqw68** [comment]
@timashev  thanks Albert..I will check it and will update you the same...

**Comment by fgqw68** [comment]
@timashev 
We tested it and it works :-)

**Comment by StanislavVolodarskiy** [comment]
Master has been updated recently. Please resolve conflicts.

**Comment by fgqw68** [comment]
@timashev  Figured out why camerabase.cs was not getting created in my case. That issue needs to be fixed. CameraBase.cs will not be regenerate during rake or rhogen api call, if we are not explicitly deleting generated temp folder. rake clean:wp8 does not delete generated folder under mediacapture/ext/platforms/wp8. This needs to be fixed

**Comment by fgqw68** [comment]
@StanislavVolodarskiy  sure. thanks.

**Pull request closed without merging**
