### PR TITLE
Fix double image rotation on Android

### PR DESCRIPTION
**Pull request by nhinze**
Double rotation of image occurs if:
useRealBitmapResize = true
useRotationBitmapByEXIF = tue
are used together.

### CODE REVIEW

**Comment by dimahts990** [comment]
Hi @nhinze 
Could you please let us know which version of Rhodes you were using and on which device you noticed the issue?

**Comment by nhinze** [comment]
I'm using Rhodes 7.6 and it happens at least on Pixel devices (4a and 7a)

**Comment by dimahts990** [comment]
Dear @nhinze , Thank you for your reply! We are still unable to replicate the issue you described. Could you please provide us with the following information? 
- Android version 
- Other properties used to configure the camera

**Comment by nhinze** [comment]
I use the following settings. The problem happens on Android 13 and 14.

  def take_a_picture
    
    # Settings
    cameraSettings = Hash.new
    cameraSettings['desiredWidth'] = 2048
    cameraSettings['desiredHeight'] = 2048
    cameraSettings['flashMode'] = "FLASH_AUTO"
    cameraSettings['enableEditing'] = false
    cameraSettings['useSystemViewfinder'] = true
    cameraSettings['useRealBitmapResize'] = true
    cameraSettings['useRotationBitmapByEXIF'] = true

    Rho::Camera.takePicture(cameraSettings, url_for(:action => :camera_callback, query: { mode: @params['new_or_edit']} ))

  end  

When the image is resized, it will also be rotated at line 595 with command:

`saveTransformedBitmap(bitmapPath, scaledBitmap, bitmap, rotate_angle);
`
Then it will be rotated again at line 636 with command:

`Bitmap rotated = rotateBitmap(bitmap, rotate_angle);`

because at line 627 you have:

```
		// EXIF rotation
		if (rotate_angle != 0) {
```

**Pull request merged**
