### PR TITLE
Wp8 praveen camera

### PR DESCRIPTION
**Pull request by npj473**

### CODE REVIEW

**Comment by npj473** [comment]
@timashev  Hi Albert, can you please review a file named Montana_Impl.cpp. We have removed overriden methods as discussed over the mail. need your confirmation on that file

**Comment by timashev** [comment]
@npj473 I have reviewed your changes and everything looks alright. Are you ready to merge your work to master branch?

**Comment by npj473** [comment]
Once the Review is done, Thought of merging it to Main Branch

**Comment by fgqw68** [comment]
@npj473  I too completed review. Accept as is. 
@timashev  Thanks a lot for your great support.

**Comment by fgqw68** [comment]
@timashev  I think he may have to supported getsupported resolution (where you given fix for list of dictionaries).

**Comment by timashev** [comment]
@fgqw68 OK, then let @npj473 merge changes from master branch (required to support hash of hashes and vector of hashes as a result) and implement getSupportedResolutions. Then we'll merge.

**Comment by fgqw68** [comment]
@timashev  sure

**Comment by npj473** [comment]
Hey Albert, have verified the fix provided and its working thank you Albert.

**Comment by timashev** [comment]
@npj473 I have made minor changes to .props files and WMAppManifest.xml file. To build from Visual Studio you'll need to edit .props files locally (change <RHO_ROOT_> to <RHO_ROOT> and <TEMP_FILES_DIR_> to <TEMP_FILES_DIR>), but don't commit them. OK?

**Comment by npj473** [comment]
Sure Albert

**Comment by npj473** [comment]
Albert how is logger implemented in WP8…
Would like to add logger in my camera implementation class

**Comment by npj473** [comment]
I am merging these changes. Will create another pull request for supportingresolutions

**Pull request merged**
