### PR TITLE
Blr android camera

### PR DESCRIPTION
**Pull request by malayap47**

### CODE REVIEW

**Comment by fgqw68** [comment]
uncommented init_videocapture

**Comment by StanislavVolodarskiy** [comment]
Closed due to a compilations failure: http://zru11mac01.spb.mot.com:8080/jenkins/job/t2_build_rhosimulator_mac/1296/console

**Comment by StanislavVolodarskiy** [comment]
Reopened after reported fix.

**Comment by malayap47** [comment]
Hence merging the branch as build is sucessful

**Pull request merged**
