### PR TITLE
Sr embpd00161225

### PR DESCRIPTION
**Pull request by debrajdhar**
EMBPD00161225 - [EB][WM][IE]:[EB][WM][IE]: Backbutton(html) does not function as expected on Nav timeout page

Solution- Added a link list "CHistoryElement" to store the url navigated.Added the following function 
1)AddNewUrl-Add a URL to the history list.This function is called when the event NAVIGATECOMPLETE is set.
2)GetPreviousUrl- gets the previous url is the link list when the back button is pressed.

I have refered the implementation of the following file ,
https://github.com/rhomobile/Motorola-Extensions/blob/master/neon/Helium/HeliumForWindows/Implementation/Engine/IEEngine/common/History.cpp

### CODE REVIEW

**Comment by darryncampbell** [comment]
This is a really big change, how did history in the IE engine work prior to this change?  Or did it not work at all?  Also, if it is required to make use of https://github.com/rhomobile/Motorola-Extensions/blob/master/neon/Helium/HeliumForWindows/Implementation/Engine/IEEngine/common/History.cpp could you not just copy it to this repository?

**Comment by debrajdhar** [comment]
Hi @darryncampbell as far my understanding from the code , history in IE engine for WM device was not implemented.
Regarding the 2nd part, I  didnt need the entire file, but parts of it ,that too with lots of modification.
So i didnt felt the need of separate file here..

**Comment by darryncampbell** [comment]
Just heard that history did not work at all with IE.  I still feel it would have been best to try and use the existing History.cpp/.h files BUT if you have tested this implementation and it works then the contained looks good to merge.

**Comment by debrajdhar** [comment]
Hi @darryncampbell I have tested this implementation, and its working fine.. Actually it was not possible to use the file directly, and requires a lot of modification.Also i just need a part of that file, so i made this implementation.I am merging the code

**Pull request merged**
