### PR TITLE
PT#107565930, RMS version string added

### PR DESCRIPTION
**Pull request by thanizebra**

### CODE REVIEW

**Comment by abhineetagarwal** [comment]
Please donot merge this unless this has been validated with all platform build and installation and validation of the same in the device

**Comment by thanizebra** [comment]
ok

**Comment by thanizebra** [comment]
any plan to merge ???

**Comment by motobhakta** [comment]
Currently No plan. Kindly add in readme file, what are the file changes required when new version of RMS getting released.

**Comment by abhineetagarwal** [comment]
@thanizebra : As mentioned by Bhakta, please donot merge the same...

**Pull request closed without merging**
